- name: Deploy WordPress and DB in Docker
  hosts: hosts
  become: true
  vars_files:
    - .vars.yaml
  tasks:
    - name: Ensure required dependencies are installed
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Create Docker repository file
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start MySQL container
      docker_container:
        name: wp_db
        image: mysql:latest
        env:
          MYSQL_DATABASE: "{{ wordpress_db_name }}"
          MYSQL_USER: "{{ db_user }}"
          MYSQL_PASSWORD: "{{ db_pass }}"
          MYSQL_ROOT_PASSWORD: "{{ db_root_pass }}"
        ports:
          - "3306:3306"
        state: started
        restart_policy: always

    - name: Start WordPress container
      docker_container:
        name: wordpress
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: wp_db:3306
          WORDPRESS_DB_NAME: "{{ wordpress_db_name }}"
          WORDPRESS_DB_USER: "{{ db_user }}"
          WORDPRESS_DB_PASSWORD: "{{ db_pass }}"
        ports:
          - "{{ wordpress_port }}:80"
        links:
          - wp_db
        state: started
        restart_policy: always
